### ISSUE TITLE
Check New Relic Monitoring

### ISSUE THREAD

**Issue by IcusFMagni** [PRX/meta.prx.org#119]
Check to make sure New Relic monitoring is working and properly configured.

**Comment by cavis** [comment]
I'm not entirely sure what this means?  But I assume it's in reference to frontend monitoring on Publish.  Which I did confirm is correctly coming into our [NR free account](https://rpm.newrelic.com/accounts/43935/browser/24356856).  It's just not very useful, because it doesn't report JS errors, and I _think_ it's only showing page loads.  (Not Angular route changes, and those CMS load times).

I think @pstjean has a ticket to look into other frontend monitoring tools that might give us better insight than NR.
